build: disable `win_arm64` for now
build fails when compiling `xee-xpath-macros` (lib) with:

> error: linking with `link.exe` failed: exit code: 1120

because of an

> error LNK2019: unresolved external symbol